import puppeteer from "puppeteer";
import path from "path";
import fs from "fs/promises";

interface FormData {
  _id: string;
  name: string;
  email: string;
  age: string;
  message: string;
  gptResponse?: string;
}

class PdfService {
  private pdfDir = path.join(__dirname, "../../pdfs");

  constructor() {
    this.ensurePdfDirectory();
  }

  private async ensurePdfDirectory(): Promise<void> {
    try {
      await fs.mkdir(this.pdfDir, { recursive: true });
      console.log("📁 PDF directory ready:", this.pdfDir);
    } catch (error) {
      console.error("Error creating PDF directory:", error);
    }
  }

  async generatePdf(formData: FormData): Promise<string> {
    const browser = await puppeteer.launch({
      headless: true,
      args: ["--no-sandbox", "--disable-setuid-sandbox"],
    });

    try {
      const page = await browser.newPage();

      const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>eKYC Report - ${formData.name}</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      padding: 40px;
      color: #333;
      background: #f9f9f9;
    }
    .container {
      max-width: 800px;
      margin: 0 auto;
      background: white;
      padding: 40px;
      border-radius: 8px;
      box-shadow: 0 2px 10px rgba(0,0,0,0.1);
    }
    .header {
      text-align: center;
      margin-bottom: 40px;
      padding-bottom: 20px;
      border-bottom: 3px solid #3b82f6;
    }
    .header h1 {
      font-size: 28px;
      color: #1e40af;
      margin-bottom: 10px;
    }
    .header p {
      color: #666;
      font-size: 14px;
    }
    .section {
      margin-bottom: 30px;
    }
    .section-title {
      font-size: 18px;
      font-weight: 600;
      color: #1e40af;
      margin-bottom: 15px;
      padding-bottom: 8px;
      border-bottom: 2px solid #e5e7eb;
    }
    .field {
      margin-bottom: 20px;
    }
    .field-label {
      font-size: 12px;
      font-weight: 600;
      color: #6b7280;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      margin-bottom: 5px;
    }
    .field-value {
      font-size: 16px;
      color: #111827;
      padding: 10px;
      background: #f3f4f6;
      border-radius: 4px;
      min-height: 40px;
    }
    .field-value.long {
      white-space: pre-wrap;
      line-height: 1.6;
    }
    .footer {
      margin-top: 50px;
      padding-top: 20px;
      border-top: 1px solid #e5e7eb;
      text-align: center;
      color: #9ca3af;
      font-size: 12px;
    }
    .metadata {
      display: flex;
      justify-content: space-between;
      margin-top: 10px;
      font-size: 11px;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>eKYC Report</h1>
      <p>Electronic Know Your Customer Form</p>
      <div class="metadata">
        <span>Document ID: ${formData._id}</span>
        <span>Generated: ${new Date().toLocaleString()}</span>
      </div>
    </div>

    <div class="section">
      <div class="section-title">Personal Information</div>
      
      <div class="field">
        <div class="field-label">Full Name</div>
        <div class="field-value">${formData.name || "N/A"}</div>
      </div>

      <div class="field">
        <div class="field-label">Email Address</div>
        <div class="field-value">${formData.email || "N/A"}</div>
      </div>

      <div class="field">
        <div class="field-label">Age</div>
        <div class="field-value">${formData.age || "N/A"}</div>
      </div>
    </div>

    <div class="section">
      <div class="section-title">Message</div>
      <div class="field">
        <div class="field-value long">${formData.message || "N/A"}</div>
      </div>
    </div>

    ${
      formData.gptResponse
        ? `
    <div class="section">
      <div class="section-title">AI Analysis</div>
      <div class="field">
        <div class="field-value long">${formData.gptResponse}</div>
      </div>
    </div>
    `
        : ""
    }

    <div class="footer">
      <p>This document was automatically generated by the eKYC system.</p>
      <p>For verification purposes only. Do not share without authorization.</p>
    </div>
  </div>
</body>
</html>
      `;

      await page.setContent(htmlContent, { waitUntil: "networkidle0" });

      const pdfPath = path.join(
        this.pdfDir,
        `ekyc_${formData._id}_${Date.now()}.pdf`
      );

      await page.pdf({
        path: pdfPath,
        format: "A4",
        printBackground: true,
        margin: {
          top: "20px",
          right: "20px",
          bottom: "20px",
          left: "20px",
        },
      });

      console.log(`✅ PDF generated: ${pdfPath}`);
      return pdfPath;
    } finally {
      await browser.close();
    }
  }
}

export default new PdfService();
